sudo: required
services:
    - docker

before_install:
    - docker build -t example -f Dockerfile.dev .

script:
    - docker run example npm run test

language: generic

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "example"
    env: "example"
    bucket_name: "example"
    bucket_path: "example"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY