version: '3'

services:
  nodejsserver:
    build: .
    container_name: nodejsserver
    command: npm run dev
    restart: always
    env_file: .env
    ports:
        - ${HOST_PORT:-80}:80
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
